name: Sync icons from Figma
on:
  # schedule:
  # At 09:00 on every day-of-week from Monday through Friday
  # - cron: "0 9 * * 1-5"
  # push:

jobs:
  all:
    name: Sync icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production"

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: "10.x"

      # # Persist the yarn cache between builds, unless yarn.lock changes
      # - name: Get yarn cache
      #   id: yarn-cache
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: Install Dependencies
      #   run: yarn install

      - uses: chasemccoy/figma-action@1.0.0-alpha.5
        with:
          args: "format=svg outputDir=./figma"
        env:
          # This points to the Figma URL of our current icon kit
          FIGMA_FILE_URL: "https://www.figma.com/file/24t2Qvzhiga5K1oDCQJbLp/Mistica-Icons"
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      # Move the output files to our icons folder and run the icon linter on them
      - run: |
          sudo cp -R ./figma/svg/. ./fig-icons/
          sudo rm -r ./figma

      # Create a PR if there are any file diffs
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync icons with Figma"
          title: "Sync icons from Figma"
          branch: "figma-icon-sync"
          base: "production"
          body: |
            🚨 **This pull request has been created automatically** 🚨

            Racine uses a GitHub action to sync the svg files for our icons from our [Mística Icons in Figma](https://www.figma.com/file/JHuzksh01yxExMeMQBvymq/Beta-Mistica-Icons). This script runs everyday at 09:00.

            Whenever you need to release any icon changes into Mística Icons, you can merge this PR publishing a new version in production branch.

            **Be sure to take a look at the changes files to make sure everything is in order before merging.**
