blank_issues_enabled: false
contact_links:
  - name: Icon request ✨
    url: https://github.com/Telefonica/mistica-design/issues/new?assignees=&labels=fundamentals%3A+icons%2Crequest+%E2%9C%A8&template=icon_request.yml&title=Title
    about: Request icons improvements or needs
  - name: Bug report 🐛
    url: https://github.com/Telefonica/mistica-design/issues/new?assignees=&labels=bug+%F0%9F%90%9E&template=bug_report.yml&title=Bug+title
    about: Create a report to help us improve the Mística libraries
  - name: Component request ✨
    url: https://github.com/Telefonica/mistica-design/discussions/new
    about: Request improvements or needs
  - name: Questions
    url: https://teams.microsoft.com/l/team/19%3ad2e3607a32ec411b8bf492f43cd0fe0c%40thread.tacv2/conversations?groupId=e265fe99-929f-45d1-8154-699649674a40&tenantId=9744600e-3e04-492e-baa1-25ec245c6f10
    about: Please ask questions in our Microsoft Teams.
