name: Cloning icn_export to mistica-icon-web

on: 
  workflow_run:
    workflows: ["SketchTool Export Assets"]
    branches:
      - production
    types: 
      - completed

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: production
        src_path: icn_export/.
        dst_path: icn_export/.
        dst_branch: master
        dst_owner: Telefonica
        dst_repo_name: mistica-icons-web
        clean: true
        commit_message: Icons uploaded to master

    # Para el self-hosted (Raspi)
    # - run: sudo chown -R $USER:$USER /home/pi/actions-runner/_work/mistica-icons
    # - run: rm -r /home/pi/actions-runner/_work/mistica-icons/mistica-icons
