name: SketchTool Export Assets

on:
  push:
    branches:
    - production
    paths:
    - '_library/**'

jobs:
  assets:
    runs-on: self-hosted #macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2

    - name: install svgo
      run: sudo npm install -g svgo

    - name: removed assets
      run: |
        git rm -r asset_auto_exported/**
    
    - run: sudo npm install --global kactus-cli

    - name: convert folder to sketch file
      run: |
        kactus import _library/Icon_Library

    - name: Download & Install Sketch
      run: |
        curl -OL https://sketch.com/download/sketch.zip
        unzip sketch.zip

    - name: Run SketchTool
      run: Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export layers --output=asset_auto_exported _library/*.sketch


    - name: add assets
      run: svgo asset_auto_exported/*.svg --disable=removeViewBox


    - name: add assets
      run: |
        git add -A asset_auto_exported/*

    - name: config
      run: |
        git config --global user.name "🤖GeneratorBot"
        git config --global user.email "users.noreply.github.com"     
    
    - name: commit
      run: |    
        git commit -am "Update Assets"

    - name: push
      run: |
        git show-ref
        git push origin HEAD:production
