name: Readme Generator

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/md-generator/md-generator.py'
      - '.github/workflows/auto-generator.yml'
  workflow_run:
    workflows: ["SketchTool Export Assets"]
    types:
      - completed

jobs:
  regenerating:
    runs-on: [self-hosted, macOS]

    steps:
      # comando solo para Self-Hosted machines
      - run: sudo chown -R $USER:$USER /home/pi/Actions/mistica-icons/_work/
      - name: Cleanup
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - uses: actions/checkout@v2

      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - run: sudo python3 .github/md-generator/md-generator.py icons

      - name: Commit & Push
        run: |
          git config user.name "Bot"
          git config user.email "nobody@nowhere"  
          git commit -am "Update readme"
          git push origin ${{ env.GITHUB_REF_SLUG_URL }}

    # - name: push code to ${{ env.GITHUB_REF_SLUG_URL }}
    #   run: git push origin HEAD:${{ env.GITHUB_REF_SLUG_URL }}