name: Readme Generator

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/md-generator/md-generator.py'
      - '.github/workflows/auto-generator.yml'
      - 'icons/**'
  workflow_dispatch:


jobs:
  regenerating:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - run: sudo python3 .github/md-generator/md-generator.py icons

      - name: Commit & Push
        run: |
          git config user.name "Bot"
          git config user.email "nobody@nowhere"  
          git commit -am "Update readme"
          git push origin ${{ env.GITHUB_REF_SLUG_URL }}
