name: Readme Generator

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/md-generator/generate_markdown.py"
      - ".github/md-generator/generate_icon_table.py"
      - ".github/md-generator/generate_graph.py"
      - ".github/workflows/auto-generator.yml"
      - "icons/"

jobs:
  readme-generator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - run: sudo python3 .github/md-generator/generate_markdown.py icons

      - name: Commit & Push in ${{ env.GITHUB_REF_SLUG_URL }}
        run: |
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "update changelog"
          git push origin ${{ env.GITHUB_REF_SLUG_URL }}
