name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert to PDF
        run: |
          brew install librsvg
          ./svg-resizer.js -e pdf -o icons/resized/ icons/*.svg
          git add -A