name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Convert to PDF
      #   run: |
      #     sudo apt-get install inkscape
      #     chmod +x .github/md-generator/svg2pdf.sh
      #     bash .github/md-generator/svg2pdf.sh ./icons/*.svg
      #     git add -A

      - name: Convert SVG to PDF
        run: |
          sudo apt-get install librsvg2-bin
          find icons/ -type f -name "*.svg" ! rsvg-convert -f pdf -o *.pdf *.svg
          git config user.name "Bot"
          git config user.email "nobody@nowhere"  
          git commit -am "Update figma icons"
          git add -A
          git push origin figma-export-workflow