name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert to PDF
        run: |
          sudo apt-get install -y libgbm-dev
          svg2pdf icons/*.svg icons/*.pdf
          git add -A