name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert to PDF
        run: |
          sudo apt-get install inkscape
          find ./icons/* -name "*.svg" -exec sh -c 'inkscape $1 --export-pdf=${1%.svg}.pdf' _ {} \;
          git add -A