name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Convert to PDF
      #   run: |
      #     sudo apt-get install inkscape
      #     chmod +x .github/md-generator/svg2pdf.sh
      #     bash .github/md-generator/svg2pdf.sh ./icons/*.svg
      #     git add -A

      - name: Convert SVG to PDF
        run: |
          sudo apt-get install librsvg2-bin
          for i in icons/*.svg; do rsvg-convert -f pdf -o ${i%.*}.pdf $i;done
          git add -A