name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert to PDF
        run: |
          npm install -g svg2pdf-cli
          svg2pdf icons/*.svg icons/*.pdf
          git add -A