name: convert svg to pdf

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert to PDF
        run: |
          sudo apt-get install inkscape
          sudo ln -s /Applications/Inkscape.app/Contents/MacOS/inkscape /usr/local/bin/inkscape
          chmod +x .github/md-generator/svg2pdf.sh
          bash svg2pdf.sh ./icons
          git add -A